dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install codecov
script:
- make
- make devel
- make install
- make test
notifications:
  email:
    recipients:
    - jesse_cooper@codeholics.com
    on_success: never
    on_failure: always
after_success:
- codecov
deploy:
  provider: pypi
  user: jessecooper
  password:
    secure: J3fUkVNt4441xVPmhZJO1WnB1FXL+R3ij36W74xIZOMZvS5ZpvXUWCXW45+L07ucq3C+hNbBa9TLlIlI0dUr7aZxUtuhLNeCX/SNHZI8nPVfy6cmr8wWIa22EfCBa3MlSZMiuF37fvwpBPPIWgsZeo+iD3jmRiIsPmplcyIegGhs4yT+sLvWz8TBavpJavmL5z/+Mw3xZZZYZzajtxnPNRAENBIVfQwifTOrdm+FSTZTwZ+N9bGQArfWzPJ1P8LjjGF9wcOWnVPYp1rzjrdmsE9yIzQ4UoX2frz8fwrHgdZoK4tBaz7/wTW4MHPDy9zY6XnM9LbpPAK5dJo6fwGktKuJ4RDG9rcl6dh2G0iUTifTt25IgVlwIzts5KYLk9xXlpxxsNuRX0HSTFCWiJh0QPs+RD0NZAJ0FFILbg6HfK7d7N0+IB4w98wlSxTfnM8mD+MQeUWfBuHtG7EvU04KI6Ypk1mq69juiudKLwDvdm2UedKgu17zSmzbOGLoxNh7X10kuKrrP8z8rZqSJiKzNHwa4hjvroSC1MqPPq6QnIexW0Vd4FShgyFnEBkpQtdvPp3cuwTn2iJdk4i1hDu0vI+wQysiNZc6gQyGbUktxd6jIdQvvEHnYDZsDVJD4yYCSG1xZWqLVDQmk/tl9sEykUDKjk7XLw8QWz953KEUZCs=
  on:
    tags: true
